global:
  cluster: monitoring

  projects:
    kyverno-app:
      description: 'kyverno'
      sourceRepos:
      - git@github.com:paas2/prometheus.git
      destinations:
        namespaces:
        - monitoring
        - kube-system
      extraFields: |
        clusterResourceWhitelist:
        - group: '*'
          kind: '*' 

    fluentbit:
      description: 'fluent-bit'
      sourceRepos:
      - git@github.com:paas2/ad-integration.git
      destinations:
        namespaces:
        - ad-integration
      extraFields: |
        clusterResourceWhitelist:
        - group: '*'
          kind: '*'           
                              
  applications:
    kyverno-app:
      destination:
        namespace: kyverno
      project: kyverno-app
      source:
        path: helm-charts/kube-prometheus
        repoURL: git@github.com:paas2/prometheus.git   
        extraSourceFields: |
          helm:
            valueFiles:
            - values.yaml   
            - values-{{ $.Values.global.cluster }}-{{ $.Values.global.envName }}.yaml

    fluentbit:
      destination:
        namespace: fluentbit
      project: fluentbit
      source:
        path: helm-charts/ad-integration
        repoURL: git@github.com:paas2/ad-integration.git     
        extraSourceFields: |
          helm:
            valueFiles:
            - values.yaml   
            - values-{{ $.Values.global.cluster }}-{{ $.Values.global.envName }}.yaml   
